### ISSUE TITLE
Shiny app: Add option to select published data only

### ISSUE THREAD

**Issue by ChHaeni** [sashahafner/ALFAM2-data#33]
Sorry if this is the wrong place to address issues related to the database interface with the shiny app.

I just realized that there is a mixture of unpublished and published data available in the database. I think there should be an option to filter for published data in the shiny app interface.

Also, it would be nice, if one could filter for data including incorporation.

**Comment by sashahafner** [comment]
Here is fine. 
I just noticed this though.
The incorporation option should be easy.
A published filter might be too.

**Comment by sashahafner** [comment]
@ChHaeni I've added these filters to a "dev" version.
Can you check it out before I push it to the main version?
<https://biotransformers.shinyapps.io/ALFAM2-dev/>
I'll update the data soon too (#35 )

**Comment by ChHaeni** [comment]
@sashahafner perfect! thanks for adding these options!

**Comment by sashahafner** [comment]
You are welcome!
Now deployed here as well: 
<https://biotransformers.shinyapps.io/ALFAM2/>
